# This file stores configurations for your Shopify app.

scopes = "write_products,write_draft_orders,write_orders,read_orders,read_draft_orders,read_themes,write_themes,read_price_rules,read_discounts,read_customers"
